/* Generated by AN DISI Unibo */ 
package it.unibo.sourcehandler;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
public abstract class AbstractSourcehandler extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	 
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}
		public AbstractSourcehandler(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/sourcehandler/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");		
			this.planFilePath = "./srcMore/it/unibo/sourcehandler/plans.txt";
	  	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("handlematerialAvailable",handlematerialAvailable);
	    	stateTab.put("lgvNotReady",lgvNotReady);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "sourcehandler tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("init",-1);
	    	String myselfName = "init";  
	    	temporaryStr = "\"sourcehandler WORKING\"";
	    	println( temporaryStr );  
	    	//bbb
	     msgTransition( pr,myselfName,"sourcehandler_"+myselfName,false,
	          new StateFun[]{stateTab.get("handlematerialAvailable") },//new StateFun[]
	          new String[]{"true","M","materialAvailable" },
	          600000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun handlematerialAvailable = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("handlematerialAvailable",-1);
	    	String myselfName = "handlematerialAvailable";  
	    	printCurrentMessage(false);
	    	temporaryStr = "\"A new source is engaged. Now I send qLaod to smarttm by expecting s200LgvReady\"";
	    	println( temporaryStr );  
	    	//onMsg 
	    	curT = Term.createTerm("sourceEngaged(S)");
	    	if( currentMessage != null && currentMessage.msgId().equals("materialAvailable") && 
	    		pengine.unify(curT, Term.createTerm("sourceEngaged(SOURCE)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		String parg="qLoad_1(S)";
	    		/* SendDispatch */
	    		parg = updateVars(Term.createTerm("sourceEngaged(SOURCE)"),  Term.createTerm("sourceEngaged(S)"), 
	    			    		  					Term.createTerm(currentMessage.msgContent()), parg);
	    		if( parg != null ) sendMsg("qLoad_1","smarttm", QActorContext.dispatch, parg ); 
	    	}
	    	//bbb
	     msgTransition( pr,myselfName,"sourcehandler_"+myselfName,true,
	          new StateFun[]{
	          () -> {	//AD HOC state to execute an action and resumeLastPlan
	          try{
	            PlanRepeat pr1 = PlanRepeat.setUp("adhocstate",-1);
	            //ActionSwitch for a message or event
	             if( currentMessage.msgContent().startsWith("s200LgvReady") ){
	            	String parg="s200LgvReady(SOURCE,LGV)";
	            	/* SendDispatch */
	            	parg = updateVars(Term.createTerm("s200LgvReady(SOURCE,LGV)"),  Term.createTerm("s200LgvReady(SOURCE,LGV)"), 
	            		    		  					Term.createTerm(currentMessage.msgContent()), parg);
	            	if( parg != null ) sendMsg("s200LgvReady","lgvman", QActorContext.dispatch, parg ); 
	             }
	            repeatPlanNoTransition(pr1,"adhocstate","adhocstate",false,true);
	          }catch(Exception e ){  
	             println( getName() + " plan=handlematerialAvailable WARNING:" + e.getMessage() );
	             //QActorContext.terminateQActorSystem(this); 
	          }
	          }
	          },//new StateFun[]
	          new String[]{"true","M","s200LgvReady" },
	          2000, "lgvNotReady" );//msgTransition
	    }catch(Exception e_handlematerialAvailable){  
	    	 println( getName() + " plan=handlematerialAvailable WARNING:" + e_handlematerialAvailable.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//handlematerialAvailable
	    
	    StateFun lgvNotReady = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("lgvNotReady",-1);
	    	String myselfName = "lgvNotReady";  
	    	temporaryStr = "\"No LGV is ready\"";
	    	println( temporaryStr );  
	    	repeatPlanNoTransition(pr,myselfName,"sourcehandler_"+myselfName,false,true);
	    }catch(Exception e_lgvNotReady){  
	    	 println( getName() + " plan=lgvNotReady WARNING:" + e_lgvNotReady.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//lgvNotReady
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
	}
