/* Generated by AN DISI Unibo */ 
package it.unibo.sourcehandler;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Sourcehandler extends QActorMsgQueue{
	public MsgHandle_Sourcehandler(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
