/* Generated by AN DISI Unibo */ 
package it.unibo.qambotpc;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Qambotpc extends QActorMsgQueue{
	public MsgHandle_Qambotpc(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
