/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.qabls0client;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;
import it.unibo.rest.clienthttp.RestClientHttp;

public class Qabls0client extends AbstractQabls0client { 
	public Qabls0client(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
	public void sendPut(String msg, int port) {
		RestClientHttp.setCtx( this.getQActorContext() );
		RestClientHttp.sendPut(msg, "http://localhost:"+port);
		
	}
//	public void work1( ) {
////		System.out.println("RestClientHttp");
//		RestClientHttp.setCtx( this.getQActorContext() );
// 		RestClientHttp.connectGet();
//		RestClientHttp.sendPut("{\"value\":false}", "http://localhost:8484/pi/actuators/leds/2");
//		RestClientHttp.sendPut("{\"value\":true}", "http://localhost:8484/pi/actuators/leds/1");
//		RestClientHttp.connectGet();	
//		RestClientHttp.setCtx( null );
// 	}

}
