/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.ledtester;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Ledtester extends AbstractLedtester { 
	public Ledtester(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
