/* Generated by AN DISI Unibo */ 
package it.unibo.qacontrolhlblinkreactive;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Qacontrolhlblinkreactive extends QActorMsgQueue{
	public MsgHandle_Qacontrolhlblinkreactive(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
