/* Generated by AN DISI Unibo */ 
package it.unibo.lgvman;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
public abstract class AbstractLgvman extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	 
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}
		public AbstractLgvman(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/lgvman/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");		
			this.planFilePath = "./srcMore/it/unibo/lgvman/plans.txt";
	  	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("doWork",doWork);
	    	stateTab.put("handlematerialAvailable",handlematerialAvailable);
	    	stateTab.put("handles200LgvReady",handles200LgvReady);
	    	stateTab.put("handles300LgvLoaded",handles300LgvLoaded);
	    	stateTab.put("handlenmis",handlenmis);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "lgvman tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("init",-1);
	    	String myselfName = "init";  
	    	it.e80.customGui.createCustomGui( this ,"400", "10", "20", "white"  );
	    	//switchTo doWork
	        switchToPlanAsNextState(pr, myselfName, "lgvman_"+myselfName, 
	              "doWork",false, false, null); 
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun doWork = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp(getName()+"_doWork",0);
	     pr.incNumIter(); 	
	    	String myselfName = "doWork";  
	    	//bbb
	     msgTransition( pr,myselfName,"lgvman_"+myselfName,false,
	          new StateFun[]{stateTab.get("handlematerialAvailable"), stateTab.get("handles200LgvReady"), stateTab.get("handles300LgvLoaded"), stateTab.get("handlenmis") },//new StateFun[]
	          new String[]{"true","M","materialAvailable", "true","M","s200LgvReady", "true","M","s300LgvLoaded", "true","M","nmis" },
	          600000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_doWork){  
	    	 println( getName() + " plan=doWork WARNING:" + e_doWork.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//doWork
	    
	    StateFun handlematerialAvailable = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("handlematerialAvailable",-1);
	    	String myselfName = "handlematerialAvailable";  
	    	temporaryStr = "\"A new source is engaged. Now I send qLaod to smarttm by expecting s200LgvReady\"";
	    	println( temporaryStr );  
	    	//onMsg 
	    	curT = Term.createTerm("sourceEngaged(S)");
	    	if( currentMessage != null && currentMessage.msgId().equals("materialAvailable") && 
	    		pengine.unify(curT, Term.createTerm("sourceEngaged(SOURCE)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		String parg="qLoad(S)";
	    		/* SendDispatch */
	    		parg = updateVars(Term.createTerm("sourceEngaged(SOURCE)"),  Term.createTerm("sourceEngaged(S)"), 
	    			    		  					Term.createTerm(currentMessage.msgContent()), parg);
	    		if( parg != null ) sendMsg("qLoad","smarttm", QActorContext.dispatch, parg ); 
	    	}
	    	repeatPlanNoTransition(pr,myselfName,"lgvman_"+myselfName,false,true);
	    }catch(Exception e_handlematerialAvailable){  
	    	 println( getName() + " plan=handlematerialAvailable WARNING:" + e_handlematerialAvailable.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//handlematerialAvailable
	    
	    StateFun handles200LgvReady = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("handles200LgvReady",-1);
	    	String myselfName = "handles200LgvReady";  
	    	printCurrentMessage(false);
	    	temporaryStr = "\"A lgv is ready. Now I send m200LoadConfirmed to smarttm\"";
	    	println( temporaryStr );  
	    	//onMsg 
	    	curT = Term.createTerm("s200LgvReady(SOURCE,LGV)");
	    	if( currentMessage != null && currentMessage.msgId().equals("s200LgvReady") && 
	    		pengine.unify(curT, Term.createTerm("s200LgvReady(SOURCE,LGV)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		String parg="m200LoadConfirmed(SOURCE,LGV)";
	    		/* SendDispatch */
	    		parg = updateVars(Term.createTerm("s200LgvReady(SOURCE,LGV)"),  Term.createTerm("s200LgvReady(SOURCE,LGV)"), 
	    			    		  					Term.createTerm(currentMessage.msgContent()), parg);
	    		if( parg != null ) sendMsg("m200LoadConfirmed","smarttm", QActorContext.dispatch, parg ); 
	    	}
	    	repeatPlanNoTransition(pr,myselfName,"lgvman_"+myselfName,false,true);
	    }catch(Exception e_handles200LgvReady){  
	    	 println( getName() + " plan=handles200LgvReady WARNING:" + e_handles200LgvReady.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//handles200LgvReady
	    
	    StateFun handles300LgvLoaded = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("handles300LgvLoaded",-1);
	    	String myselfName = "handles300LgvLoaded";  
	    	printCurrentMessage(false);
	    	temporaryStr = "\"The lgv is loaded. Now I send pkup to sdm\"";
	    	println( temporaryStr );  
	    	//onMsg 
	    	curT = Term.createTerm("s300LgvLoaded(MATERIAL,SOURCE,LGV)");
	    	if( currentMessage != null && currentMessage.msgId().equals("s300LgvLoaded") && 
	    		pengine.unify(curT, Term.createTerm("s300LgvLoaded(MATERIAL,SOURCE,LGV)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		String parg="pkup(MATERIAL,SOURCE,LGV)";
	    		/* SendDispatch */
	    		parg = updateVars(Term.createTerm("s300LgvLoaded(MATERIAL,SOURCE,LGV)"),  Term.createTerm("s300LgvLoaded(MATERIAL,SOURCE,LGV)"), 
	    			    		  					Term.createTerm(currentMessage.msgContent()), parg);
	    		if( parg != null ) sendMsg("pkup","sdm", QActorContext.dispatch, parg ); 
	    	}
	    	repeatPlanNoTransition(pr,myselfName,"lgvman_"+myselfName,false,true);
	    }catch(Exception e_handles300LgvLoaded){  
	    	 println( getName() + " plan=handles300LgvLoaded WARNING:" + e_handles300LgvLoaded.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//handles300LgvLoaded
	    
	    StateFun handlenmis = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("handlenmis",-1);
	    	String myselfName = "handlenmis";  
	    	printCurrentMessage(false);
	    	temporaryStr = "\"A new mission must start. Now I send m100Mission to smarttm\"";
	    	println( temporaryStr );  
	    	//onMsg 
	    	curT = Term.createTerm("mission(ORDREF,DEST)");
	    	if( currentMessage != null && currentMessage.msgId().equals("nmis") && 
	    		pengine.unify(curT, Term.createTerm("mission(ORDREF,DEST)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		String parg="m100Mission(mission(ORDREF,DEST))";
	    		/* SendDispatch */
	    		parg = updateVars(Term.createTerm("mission(ORDREF,DEST)"),  Term.createTerm("mission(ORDREF,DEST)"), 
	    			    		  					Term.createTerm(currentMessage.msgContent()), parg);
	    		if( parg != null ) sendMsg("m100Mission","smarttm", QActorContext.dispatch, parg ); 
	    	}
	    	repeatPlanNoTransition(pr,myselfName,"lgvman_"+myselfName,false,true);
	    }catch(Exception e_handlenmis){  
	    	 println( getName() + " plan=handlenmis WARNING:" + e_handlenmis.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//handlenmis
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
	}
