/* Generated by AN DISI Unibo */ 
package it.unibo.lgvman;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Lgvman extends QActorMsgQueue{
	public MsgHandle_Lgvman(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
