/* Generated by AN DISI Unibo */ 
package it.unibo.qaledhlreactiveweb;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Qaledhlreactiveweb extends QActorMsgQueue{
	public MsgHandle_Qaledhlreactiveweb(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
