/* Generated by AN DISI Unibo */ 
package it.unibo.sensorsonar;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
public abstract class AbstractSensorsonar extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	 
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}
		public AbstractSensorsonar(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/sensorsonar/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");		
			this.planFilePath = "./srcMore/it/unibo/sensorsonar/plans.txt";
	  	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("dopublish",dopublish);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "sensorsonar tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("init",-1);
	    	String myselfName = "init";  
	    	//ConnectToPublish
	    	connectToSend( this.getName(), "tcp://m2m.eclipse.org:1883", "unibo/mqtt/radar");
	    	//switchTo dopublish
	        switchToPlanAsNextState(pr, myselfName, "sensorsonar_"+myselfName, 
	              "dopublish",false, false, null); 
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun dopublish = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp(getName()+"_dopublish",0);
	     pr.incNumIter(); 	
	    	String myselfName = "dopublish";  
	    	//delay  ( no more reactive within a plan)
	    	aar = delayReactive(1500,"" , "");
	    	if( aar.getInterrupted() ) curPlanInExec   = "dopublish";
	    	if( ! aar.getGoon() ) return ;
	    	if( (guardVars = QActorUtils.evalTheGuard(this, " !?dataToPublish(Q,D,A)" )) != null ){
	    	//PublishMsgMove
	    	parg = "p(D,A)";
	    	parg = QActorUtils.substituteVars(guardVars,parg);
	    	sendMsgMqtt(  "unibo/mqtt/radar", "polarMsg", guardVars.get("Q"), parg );
	    	}
	    	else{ println( "sensorsonar ends" ); 
	    	pr.terminate(); return;
	    	}
	    	repeatPlanNoTransition(pr,myselfName,"sensorsonar_"+myselfName,true,false);
	    }catch(Exception e_dopublish){  
	    	 println( getName() + " plan=dopublish WARNING:" + e_dopublish.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//dopublish
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
	}
