/* Generated by AN DISI Unibo */ 
package it.unibo.sensorsonar;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Sensorsonar extends QActorMsgQueue{
	public MsgHandle_Sensorsonar(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
