/* Generated by AN DISI Unibo */ 
package it.unibo.qafilechange;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Qafilechange extends QActorMsgQueue{
	public MsgHandle_Qafilechange(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
