/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.radarguibase;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Radarguibase extends AbstractRadarguibase { 
	public Radarguibase(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
	public void activateGui() {
		println("activateGui: wait a minute ...");
	}
	
	public void sendDataToGui( int distance, int angle ){
		println(this.getName() + "  distance=" + distance + " angle="+angle  );
 	} 
}
