/* Generated by AN DISI Unibo */ 
package it.unibo.lgv0;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Lgv0 extends QActorMsgQueue{
	public MsgHandle_Lgv0(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
