/* Generated by AN DISI Unibo */ 
package it.unibo.qacontrol;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Qacontrol extends QActorMsgQueue{
	public MsgHandle_Qacontrol(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
