/* Generated by AN DISI Unibo */ 
package it.unibo.ctxMbotControl;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainCtxMbotControl  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = "./srcMore/it/unibo/ctxMbotControl";
	return QActorContext.initQActorSystem(
		"ctxmbotcontrol", "./srcMore/it/unibo/ctxMbotControl/mbotcontrol.pl", 
		"./srcMore/it/unibo/ctxMbotControl/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	QActorContext ctx = initTheContext();
} 	
}
