/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.qahttpclient;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.web.ClientRestHttp;
 

public class Qahttpclient extends AbstractQahttpclient { 
	protected ClientRestHttp clientRest  ;

	public Qahttpclient(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
//		client = new ClientRestHttp( this.getQActorContext() );
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
 	
//	public void setConnection( String host, int port ){
//		client = new ClientRestHttp(this.getQActorContext(),host, port);
// 	}
	
//	public void sendPut(String msg) {
////		if( clientRest == null ) clientRest = new ClientRestHttp( this.getQActorContext() );
////		clientRest.sendPut( msg );
//		this.sendRestPut(msg);
//	}
//	public void sendGet() {
////		if( clientRest == null ) clientRest = new ClientRestHttp( this.getQActorContext() );
////		clientRest.sendGet();
//		this.sendRestGet();
//	}
	
	/*
	 * Useful for wot
	 */
	public void sendPut(String msg, String url) {
		msg = msg.replace("%", "\"");
		if( clientRest != null)
		clientRest.sendPut( msg,url );
	}
	public void sendGet(String url ) {
		clientRest.sendGet( url );
	}
	
	
}
