/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.qahttpclient;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;
import it.unibo.rest.clienthttp.ClientRestHttp;

public class Qahttpclient extends AbstractQahttpclient { 
	protected ClientRestHttp client  ;

	public Qahttpclient(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
		client = new ClientRestHttp( this.getQActorContext() );
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
 	
	public void setConnection( String host, int port ){
		client = new ClientRestHttp(this.getQActorContext(),host, port);
 	}
	
	public void sendPut(String msg) {
		client.sendPut( msg );
	}
	public void sendGet() {
		client.sendGet();
	}
	
	/*
	 * Useful for wot
	 */
	public void sendPut(String msg, String url) {
		msg = msg.replace("%", "\"");
		if( client != null)
		client.sendPut( msg,url );
	}
	public void sendGet(String url ) {
		client.sendGet( url );
	}
	
	
}
