/* Generated by AN DISI Unibo */ 
package it.unibo.musicreactiveasycnh;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Musicreactiveasycnh extends QActorMsgQueue{
	public MsgHandle_Musicreactiveasycnh(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
