/* Generated by AN DISI Unibo */ 
package it.unibo.qabls0client;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Qabls0client extends QActorMsgQueue{
	public MsgHandle_Qabls0client(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
