/* Generated by AN DISI Unibo */ 
package it.unibo.ctxRoverMqtt;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainCtxRoverMqtt  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = null;
	return QActorContext.initQActorSystem(
		"ctxrovermqtt", "./srcMore/it/unibo/ctxRoverMqtt/testrovermqtt.pl", 
		"./srcMore/it/unibo/ctxRoverMqtt/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	QActorContext ctx = initTheContext();
} 	
}
