/* Generated by AN DISI Unibo */ 
package it.unibo.qacontrolhlblink;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
public abstract class AbstractQacontrolhlblink extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	 
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}
		public AbstractQacontrolhlblink(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/qacontrolhlblink/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");		
			this.planFilePath = "./srcMore/it/unibo/qacontrolhlblink/plans.txt";
	  	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("waitForClick",waitForClick);
	    	stateTab.put("blink",blink);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "qacontrolhlblink tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("init",-1);
	    	String myselfName = "init";  
	    	parg = "createButtonObject(\"gui\")"; 
	    	actorOpExecute(parg, false);	//OCT17		 
	    	//switchTo waitForClick
	        switchToPlanAsNextState(pr, myselfName, "qacontrolhlblink_"+myselfName, 
	              "waitForClick",false, false, null); 
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun waitForClick = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("waitForClick",-1);
	    	String myselfName = "waitForClick";  
	    	parg = "noOp"; 
	    	actorOpExecute(parg, false);	//OCT17		 
	    	//bbb
	     msgTransition( pr,myselfName,"qacontrolhlblink_"+myselfName,false,
	          new StateFun[]{stateTab.get("blink") },//new StateFun[]
	          new String[]{"true","E","local_click" },
	          60000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_waitForClick){  
	    	 println( getName() + " plan=waitForClick WARNING:" + e_waitForClick.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//waitForClick
	    
	    StateFun blink = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp(getName()+"_blink",0);
	     pr.incNumIter(); 	
	    	String myselfName = "blink";  
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine,"switch","switch", guardVars ).toString();
	    	sendMsg("turn","qaledhl", QActorContext.dispatch, temporaryStr ); 
	    	//bbb
	     msgTransition( pr,myselfName,"qacontrolhlblink_"+myselfName,true,
	          new StateFun[]{
	          () -> {	//AD HOC state to execute an action and resumeLastPlan
	          try{
	            PlanRepeat pr1 = PlanRepeat.setUp("adhocstate",-1);
	            //ActionSwitch for a message or event
	             if( currentEvent.getMsg().startsWith("clicked") ){
	            	/* SwitchTransition */
	            	String parg = "waitForClick";
	            	parg =  updateVars( Term.createTerm("clicked(N)"), 
	            		                Term.createTerm("clicked(N)"), 
	            		                Term.createTerm(currentEvent.getMsg()), parg);
	            	if(parg != null){ 
	            		switchToPlanAsNextState(pr, myselfName, "console_"+myselfName, 
	            	    	 		    		parg,false, true, null); 
	            	    return;	
	            	    //the control is given to the caller state
	            	}
	             }
	            repeatPlanNoTransition(pr1,"adhocstate","adhocstate",false,true);
	          }catch(Exception e ){  
	             println( getName() + " plan=blink WARNING:" + e.getMessage() );
	             //QActorContext.terminateQActorSystem(this); 
	          }
	          }
	          },//new StateFun[]
	          new String[]{"true","E","local_click" },
	          300, "blink" );//msgTransition
	    }catch(Exception e_blink){  
	    	 println( getName() + " plan=blink WARNING:" + e_blink.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//blink
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
	}
