/* Generated by AN DISI Unibo */ 
package it.unibo.qaserveractivator;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Qaserveractivator extends QActorMsgQueue{
	public MsgHandle_Qaserveractivator(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
