/* Generated by AN DISI Unibo */ 
package it.unibo.musicreactive;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Musicreactive extends QActorMsgQueue{
	public MsgHandle_Musicreactive(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
