/* Generated by AN DISI Unibo */ 
package it.unibo.qahttpclient;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Qahttpclient extends QActorMsgQueue{
	public MsgHandle_Qahttpclient(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
