/* Generated by AN DISI Unibo */ 
package it.unibo.ctxE80CaseStudy;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Evh extends AbstractEvh { 
	public Evh(String name, QActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, outEnvView,eventIds);
  	}
}
