/* Generated by AN DISI Unibo */ 
package it.unibo.qacontrolhlnode;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Qacontrolhlnode extends QActorMsgQueue{
	public MsgHandle_Qacontrolhlnode(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
