/* Generated by AN DISI Unibo */ 
package it.unibo.rover;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
public abstract class AbstractRover extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	 
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}
		public AbstractRover(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/rover/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");
			this.planFilePath = "./srcMore/it/unibo/rover/plans.txt";
	  	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("waitUserCmd",waitUserCmd);
	    	stateTab.put("execMove",execMove);
	    	stateTab.put("moveForward",moveForward);
	    	stateTab.put("moveBackward",moveBackward);
	    	stateTab.put("handleSonar",handleSonar);
	    	stateTab.put("endOfMove",endOfMove);
	    	stateTab.put("handleEndOfMove",handleEndOfMove);
	    	stateTab.put("handleTout",handleTout);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "rover tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("init",-1);
	    	String myselfName = "init";  
	    	temporaryStr = "\"rover START\"";
	    	println( temporaryStr );  
	    	initUnityConnection("localhost");
	    	createSimulatedActor("rover", "Prefabs/CustomActor"); 
	    	execUnity("rover","backward",800, 70,0); //rover: default namefor virtual robot		
	    	execUnity("rover","right",1000, 70,0); //rover: default namefor virtual robot		
	    	//switchTo waitUserCmd
	        switchToPlanAsNextState(pr, myselfName, "rover_"+myselfName, 
	              "waitUserCmd",false, false, null); 
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun waitUserCmd = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp(getName()+"_waitUserCmd",0);
	     pr.incNumIter(); 	
	    	String myselfName = "waitUserCmd";  
	    	//bbb
	     msgTransition( pr,myselfName,"rover_"+myselfName,false,
	          new StateFun[]{stateTab.get("execMove") },//new StateFun[]
	          new String[]{"true","E","usercmd" },
	          600000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_waitUserCmd){  
	    	 println( getName() + " plan=waitUserCmd WARNING:" + e_waitUserCmd.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//waitUserCmd
	    
	    StateFun execMove = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("execMove",-1);
	    	String myselfName = "execMove";  
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("usercmd(robotgui(w(X)))");
	    	if( currentEvent != null && currentEvent.getEventId().equals("usercmd") && 
	    		pengine.unify(curT, Term.createTerm("usercmd(CMD)")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			/* SwitchTransition */
	    			String parg = "moveForward";
	    			parg =  updateVars( Term.createTerm("usercmd(CMD)"), 
	    				                Term.createTerm("usercmd(robotgui(w(X)))"), 
	    				                Term.createTerm(currentEvent.getMsg()), parg);
	    			if(parg != null){ 
	    				switchToPlanAsNextState(pr, myselfName, "console_"+myselfName, 
	    			    	 		    		parg,false, true, null); 
	    			    return;	
	    			    //the control is given to the caller state
	    			}
	    	}
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("usercmd(robotgui(s(X)))");
	    	if( currentEvent != null && currentEvent.getEventId().equals("usercmd") && 
	    		pengine.unify(curT, Term.createTerm("usercmd(CMD)")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			/* SwitchTransition */
	    			String parg = "moveBackward";
	    			parg =  updateVars( Term.createTerm("usercmd(CMD)"), 
	    				                Term.createTerm("usercmd(robotgui(s(X)))"), 
	    				                Term.createTerm(currentEvent.getMsg()), parg);
	    			if(parg != null){ 
	    				switchToPlanAsNextState(pr, myselfName, "console_"+myselfName, 
	    			    	 		    		parg,false, true, null); 
	    			    return;	
	    			    //the control is given to the caller state
	    			}
	    	}
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("usercmd(robotgui(a(X)))");
	    	if( currentEvent != null && currentEvent.getEventId().equals("usercmd") && 
	    		pengine.unify(curT, Term.createTerm("usercmd(CMD)")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			//println("WARNING: variable substitution not yet fully implemented " ); 
	    			execUnity("rover","left",1000, 40,0); //rover: default namefor virtual robot		
	    	}
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("usercmd(robotgui(d(X)))");
	    	if( currentEvent != null && currentEvent.getEventId().equals("usercmd") && 
	    		pengine.unify(curT, Term.createTerm("usercmd(CMD)")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			//println("WARNING: variable substitution not yet fully implemented " ); 
	    			execUnity("rover","right",1000, 40,0); //rover: default namefor virtual robot		
	    	}
	    	//onEvent 
	    	setCurrentMsgFromStore(); 
	    	curT = Term.createTerm("usercmd(robotgui(h(X)))");
	    	if( currentEvent != null && currentEvent.getEventId().equals("usercmd") && 
	    		pengine.unify(curT, Term.createTerm("usercmd(CMD)")) && 
	    		pengine.unify(curT, Term.createTerm( currentEvent.getMsg() ) )){ 
	    			//println("WARNING: variable substitution not yet fully implemented " ); 
	    			execUnity("rover","stop",10, 40,0); //rover: default namefor virtual robot		
	    	}
	    	repeatPlanNoTransition(pr,myselfName,"rover_"+myselfName,false,true);
	    }catch(Exception e_execMove){  
	    	 println( getName() + " plan=execMove WARNING:" + e_execMove.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//execMove
	    
	    StateFun moveForward = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("moveForward",-1);
	    	String myselfName = "moveForward";  
	    	Callable<String> body;
	    int ractionTimeOut=0;
	    ractionTimeOut = 30000;
	    body= new Callable<String>(){
	    	public String call() throws Exception {
	      				execUnity("rover","forward",15000, 40,0); //rover: default namefor virtual robot		
	    			return currentActionResult;
	    		}		
	    		}; 
	    		terminationEvId = QActorUtils.getNewName(IActorAction.endBuiltinEvent);
	    currentTimedAction = new ActorTimedAction("ra_"+terminationEvId,this,myCtx,body,false,
	    			terminationEvId, new String[]{}, outEnvView, ractionTimeOut	);
	    currentTimedAction.execASynch();
	      	//aaa
	    msgTransition( pr,myselfName,"rover_"+myselfName,true,
	          new StateFun[]{stateTab.get( "endOfMove"),stateTab.get( "moveBackward"),stateTab.get( "handleSonar"),stateTab.get( "execMove")},
	          new String[]{"true","E",terminationEvId,"true","E","sonarDetect","true","E","sonar","true","E","usercmd"},
	          ractionTimeOut, "handleTout" );
	    }catch(Exception e_moveForward){  
	    	 println( getName() + " plan=moveForward WARNING:" + e_moveForward.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//moveForward
	    
	    StateFun moveBackward = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("moveBackward",-1);
	    	String myselfName = "moveBackward";  
	    	Callable<String> body;
	    int ractionTimeOut=0;
	    ractionTimeOut = 30000;
	    body= new Callable<String>(){
	    	public String call() throws Exception {
	      				execUnity("rover","backward",15000, 40,0); //rover: default namefor virtual robot		
	    			return currentActionResult;
	    		}		
	    		}; 
	    		terminationEvId = QActorUtils.getNewName(IActorAction.endBuiltinEvent);
	    currentTimedAction = new ActorTimedAction("ra_"+terminationEvId,this,myCtx,body,false,
	    			terminationEvId, new String[]{}, outEnvView, ractionTimeOut	);
	    currentTimedAction.execASynch();
	      	//aaa
	    msgTransition( pr,myselfName,"rover_"+myselfName,true,
	          new StateFun[]{stateTab.get( "endOfMove"),stateTab.get( "handleSonar"),stateTab.get( "execMove")},
	          new String[]{"true","E",terminationEvId,"true","E","sonar","true","E","usercmd"},
	          ractionTimeOut, "handleTout" );
	    }catch(Exception e_moveBackward){  
	    	 println( getName() + " plan=moveBackward WARNING:" + e_moveBackward.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//moveBackward
	    
	    StateFun handleSonar = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("handleSonar",-1);
	    	String myselfName = "handleSonar";  
	    	execUnity("rover","forward",200, 40,0); //rover: default namefor virtual robot		
	    	execUnity("rover","stop",100, 40,0); //rover: default namefor virtual robot		
	    	playTheSound( "./audio/tada2.wav", 2000 );
	    	repeatPlanNoTransition(pr,myselfName,"rover_"+myselfName,false,true);
	    }catch(Exception e_handleSonar){  
	    	 println( getName() + " plan=handleSonar WARNING:" + e_handleSonar.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//handleSonar
	    
	    StateFun endOfMove = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("endOfMove",-1);
	    	String myselfName = "endOfMove";  
	    	temporaryStr = "\"endOfMove\"";
	    	println( temporaryStr );  
	    	Callable<String> body;
	    int ractionTimeOut=0;
	    ractionTimeOut = 30000;
	    body= new Callable<String>(){
	    	public String call() throws Exception {
	      				playTheSound( "./audio/music_dramatic20.wav", 1000 );
	    			return currentActionResult;
	    		}		
	    		}; 
	    		terminationEvId = QActorUtils.getNewName(IActorAction.endBuiltinEvent);
	    currentTimedAction = new ActorTimedAction("ra_"+terminationEvId,this,myCtx,body,false,
	    			terminationEvId, new String[]{}, outEnvView, ractionTimeOut	);
	    currentTimedAction.execASynch();
	      	//aaa
	    msgTransition( pr,myselfName,"rover_"+myselfName,true,
	          new StateFun[]{stateTab.get( "handleEndOfMove"),stateTab.get( "handleSonar"),stateTab.get( "execMove")},
	          new String[]{"true","E",terminationEvId,"true","E","sonar","true","E","usercmd"},
	          ractionTimeOut, "handleTout" );
	    }catch(Exception e_endOfMove){  
	    	 println( getName() + " plan=endOfMove WARNING:" + e_endOfMove.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//endOfMove
	    
	    StateFun handleEndOfMove = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("handleEndOfMove",-1);
	    	String myselfName = "handleEndOfMove";  
	    	temporaryStr = "\"handleEndOfMove\"";
	    	println( temporaryStr );  
	    	repeatPlanNoTransition(pr,myselfName,"rover_"+myselfName,false,true);
	    }catch(Exception e_handleEndOfMove){  
	    	 println( getName() + " plan=handleEndOfMove WARNING:" + e_handleEndOfMove.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//handleEndOfMove
	    
	    StateFun handleTout = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    	String myselfName = "handleTout";  
	    	temporaryStr = "\"handleTout\"";
	    	println( temporaryStr );  
	    	repeatPlanNoTransition(pr,myselfName,"rover_"+myselfName,false,false);
	    }catch(Exception e_handleTout){  
	    	 println( getName() + " plan=handleTout WARNING:" + e_handleTout.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//handleTout
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
	}
