/* Generated by AN DISI Unibo */ 
package it.unibo.qaledcustom;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Qaledcustom extends QActorMsgQueue{
	public MsgHandle_Qaledcustom(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
