/* Generated by AN DISI Unibo */ 
package it.unibo.sdm;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
public abstract class AbstractSdm extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	 
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}
		public AbstractSdm(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/sdm/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");		
			this.planFilePath = "./srcMore/it/unibo/sdm/plans.txt";
	  	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("doWork",doWork);
	    	stateTab.put("handlepkup",handlepkup);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "sdm tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("init",-1);
	    	String myselfName = "init";  
	    	it.e80.customGui.createCustomGui( this ,"400", "10", "400", "green"  );
	    	//switchTo doWork
	        switchToPlanAsNextState(pr, myselfName, "sdm_"+myselfName, 
	              "doWork",false, false, null); 
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun doWork = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp(getName()+"_doWork",0);
	     pr.incNumIter(); 	
	    	String myselfName = "doWork";  
	    	//bbb
	     msgTransition( pr,myselfName,"sdm_"+myselfName,false,
	          new StateFun[]{stateTab.get("handlepkup") },//new StateFun[]
	          new String[]{"true","M","pkup" },
	          600000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_doWork){  
	    	 println( getName() + " plan=doWork WARNING:" + e_doWork.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//doWork
	    
	    StateFun handlepkup = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("handlepkup",-1);
	    	String myselfName = "handlepkup";  
	    	printCurrentMessage(false);
	    	temporaryStr = "\"pkup received. Now I create a mission, send it to lgvman by expecting ...\"";
	    	println( temporaryStr );  
	    	//onMsg 
	    	curT = Term.createTerm("pkup(MATERIAL,SOURCE,LGV)");
	    	if( currentMessage != null && currentMessage.msgId().equals("pkup") && 
	    		pengine.unify(curT, Term.createTerm("pkup(MATERIAL,SOURCE,LGV)")) && 
	    		pengine.unify(curT, Term.createTerm( currentMessage.msgContent() ) )){ 
	    		String parg="createMission(MATERIAL,SOURCE,LGV,MISSION)";
	    		/* PHead */
	    		parg =  updateVars( Term.createTerm("pkup(MATERIAL,SOURCE,LGV)"), 
	    		                    Term.createTerm("pkup(MATERIAL,SOURCE,LGV)"), 
	    			    		  	Term.createTerm(currentMessage.msgContent()), parg);
	    			if( parg != null ) {
	    			    aar = QActorUtils.solveGoal(this,myCtx,pengine,parg,"",outEnvView,86400000);
	    				//println(getName() + " plan " + curPlanInExec  +  " interrupted=" + aar.getInterrupted() + " action goon="+aar.getGoon());
	    				if( aar.getInterrupted() ){
	    					curPlanInExec   = "handlepkup";
	    					if( aar.getTimeRemained() <= 0 ) addRule("tout(demo,"+getName()+")");
	    					if( ! aar.getGoon() ) return ;
	    				} 			
	    				if( aar.getResult().equals("failure")){
	    					if( ! aar.getGoon() ) return ;
	    				}else if( ! aar.getGoon() ) return ;
	    			}
	    	}
	    	if( (guardVars = QActorUtils.evalTheGuard(this, " !?goalResult(createMission(MATERIAL,SOURCE,LGV,MISSION))" )) != null ){
	    	temporaryStr = "MISSION";
	    	temporaryStr = QActorUtils.substituteVars(guardVars,temporaryStr);
	    	println( temporaryStr );  
	    	}
	    	if( (guardVars = QActorUtils.evalTheGuard(this, " !?goalResult(createMission(MATERIAL,SOURCE,LGV,MISSION))" )) != null ){
	    	temporaryStr = QActorUtils.unifyMsgContent(pengine,"mission(ORDREF,DEST)","MISSION", guardVars ).toString();
	    	sendMsg("nmis","lgvman", QActorContext.dispatch, temporaryStr ); 
	    	}
	    	repeatPlanNoTransition(pr,myselfName,"sdm_"+myselfName,false,true);
	    }catch(Exception e_handlepkup){  
	    	 println( getName() + " plan=handlepkup WARNING:" + e_handlepkup.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//handlepkup
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
	}
