/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.lgvtester1;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Lgvtester1 extends AbstractLgvtester1 { 
	public Lgvtester1(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
