/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.qabls0led;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Panel;

import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Qabls0led extends AbstractQabls0led { 
	public Qabls0led(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
	private Panel pled = new Panel( );
	private boolean ledState = true;	//HORRIBLE

	//OVERRIDE to exclude built-in panels
	protected void addInputPanel( int size) {};
	protected void addCmdPanels() {}
	public void createLedGui(){
 		outEnvView.getEnv().addPanel(pled);
		ledSwitch();
   	}	
	public void ledSwitch(){
		ledState = ! ledState;
 		pled.setSize( new Dimension(20,20) );	//invalidates the hierarchy
		if( ledState ) pled.setBackground(Color.green);	//on
		else pled.setBackground(Color.red);	//off
//		memoLedState();
	}
	
}
