/* Generated by AN DISI Unibo */ 
package it.unibo.ctxE80CaseStudy;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainCtxE80CaseStudy  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = "./srcMore/it/unibo/ctxE80CaseStudy";
	return QActorContext.initQActorSystem(
		"ctxe80casestudy", "./srcMore/it/unibo/ctxE80CaseStudy/e80casestudy.pl", 
		"./srcMore/it/unibo/ctxE80CaseStudy/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	QActorContext ctx = initTheContext();
} 	
}
