/* Generated by AN DISI Unibo */ 
package it.unibo.ctxBlsCustom;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Evconvert extends AbstractEvconvert { 
	public Evconvert(String name, QActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, outEnvView,eventIds);
  	}
}
