/* Generated by AN DISI Unibo */ 
package it.unibo.qaledhlcustom;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Qaledhlcustom extends QActorMsgQueue{
	public MsgHandle_Qaledhlcustom(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
