/* Generated by AN DISI Unibo */ 
package it.unibo.smarttm;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Smarttm extends QActorMsgQueue{
	public MsgHandle_Smarttm(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
