/* Generated by AN DISI Unibo */ 
package it.unibo.ctxBlsHlCustom;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainCtxBlsHlCustom  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = "./srcMore/it/unibo/ctxBlsHlCustom";
	return QActorContext.initQActorSystem(
		"ctxblshlcustom", "./srcMore/it/unibo/ctxBlsHlCustom/blshlcustom.pl", 
		"./srcMore/it/unibo/ctxBlsHlCustom/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	QActorContext ctx = initTheContext();
} 	
}
