/* Generated by AN DISI Unibo */ 
package it.unibo.ctxBlsHlBlimk;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainCtxBlsHlBlimk  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = "./srcMore/it/unibo/ctxBlsHlBlimk";
	return QActorContext.initQActorSystem(
		"ctxblshlblimk", "./srcMore/it/unibo/ctxBlsHlBlimk/blshlblink.pl", 
		"./srcMore/it/unibo/ctxBlsHlBlimk/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	QActorContext ctx = initTheContext();
} 	
}
