/* Generated by AN DISI Unibo */ 
package it.unibo.qaledhlnode;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Qaledhlnode extends QActorMsgQueue{
	public MsgHandle_Qaledhlnode(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
