/* Generated by AN DISI Unibo */ 
package it.unibo.qabls0cmdhandler;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Qabls0cmdhandler extends QActorMsgQueue{
	public MsgHandle_Qabls0cmdhandler(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
