/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.qacontrolcustom;
import it.unibo.baseEnv.basicFrame.EnvFrame;
import it.unibo.custom.gui.CustomBlsGui;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Qacontrolcustom extends AbstractQacontrolcustom { 
	public Qacontrolcustom(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
	public void  createCustomButtonObject(String devType){
		if(  devType.equals("gui")) CustomBlsGui.createCustomButtonGui(this);
// 		if( env != null) {	//env is null if we use mock
//			((EnvFrame) env).setSize(350, 300);
//			((EnvFrame) env).setLocation(50, 150);
//		}
 	}
 

}
