/* Generated by AN DISI Unibo */ 
package it.unibo.sonardetector;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Sonardetector extends QActorMsgQueue{
	public MsgHandle_Sonardetector(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
