/* Generated by AN DISI Unibo */ 
package it.unibo.lgv;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Lgv extends QActorMsgQueue{
	public MsgHandle_Lgv(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
