/* Generated by AN DISI Unibo */ 
package it.unibo.qafilechangehandler;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Qafilechangehandler extends QActorMsgQueue{
	public MsgHandle_Qafilechangehandler(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
