/* Generated by AN DISI Unibo */ 
package it.unibo.ctxRover;
import alice.tuprolog.Term;
import it.unibo.contactEvent.interfaces.IEventItem;
import it.unibo.qactors.platform.EventHandlerComponent;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.QActorUtils;

public abstract class AbstractEvh extends EventHandlerComponent { 
protected IEventItem event;
	public AbstractEvh(String name, QActorContext myCtx, IOutputEnvView outEnvView, String[] eventIds ) throws Exception {
		super(name, myCtx, eventIds, outEnvView);
  	}
	@Override
	public void doJob() throws Exception {	}
	
	public void handleCurrentEvent() throws Exception {
		event = this.currentEvent; //AKKA getEventItem();
		if( event == null ) return;
//showMsg( "---------------------------------------------------------------------" );	
showMsg( event.getPrologRep()  );				 
//showMsg( "---------------------------------------------------------------------" );	
		//RaiseOtherEvent
		{String newcontent = "p(DISTANCE,60)";
		newcontent =  updateVars( Term.createTerm("sonar(sonar1,TARGET,DISTANCE)"), 
			                Term.createTerm("sonar(sonar1,TARGET,DISTANCE)"), 
			                Term.createTerm( event.getMsg() ), newcontent);
		//println("newcontent="+newcontent);
		if( newcontent != null ){ emit( "polar", newcontent ); }
		}
		//RaiseOtherEvent
		{String newcontent = "p(DISTANCE,120)";
		newcontent =  updateVars( Term.createTerm("sonar(sonar2,TARGET,DISTANCE)"), 
			                Term.createTerm("sonar(sonar2,TARGET,DISTANCE)"), 
			                Term.createTerm( event.getMsg() ), newcontent);
		//println("newcontent="+newcontent);
		if( newcontent != null ){ emit( "polar", newcontent ); }
		}
		//RaiseOtherEvent
		{String newcontent = "p(50,90)";
		newcontent =  updateVars( Term.createTerm("sonarDetect(X)"), 
			                Term.createTerm("sonarDetect(X)"), 
			                Term.createTerm( event.getMsg() ), newcontent);
		//println("newcontent="+newcontent);
		if( newcontent != null ){ emit( "polar", newcontent ); }
		}
	}//handleCurrentEvent
	
	@Override
	protected void handleQActorEvent(IEventItem ev) {
		super.handleQActorEvent(ev);
 		try {
			handleCurrentEvent();
		} catch (Exception e) {
 			e.printStackTrace();
		}
	}//handleQActorEvent
	
}
