/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.lgv0;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Lgv0 extends AbstractLgv0 { 
	public Lgv0(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
}
