/* Generated by AN DISI Unibo */ 
package it.unibo.wharehouse;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Wharehouse extends QActorMsgQueue{
	public MsgHandle_Wharehouse(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
