/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.qaservercmds;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;


public class Qaservercmds extends AbstractQaservercmds { 
	public Qaservercmds(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
	public void sendAnswer( String serverName, String msg ) {
		sendAnswerToServer(serverName,msg);
//		try {
////			String answer= this.getName(), "answer", "nodeserver", "dispatch", "answer("+msg+")");
////			IEventItem qamsg = this.currentEvent;  
//			IConnInteraction conn = ReceiverAgent.externalEventConns.get( serverName  );
////			println("sendAnswer conn= " + conn);
//			if( conn != null ) conn.sendALine("answer("+msg+")");
//		} catch (Exception e) {
//// 			e.printStackTrace();
//			println("sendAnswer ERROR " + e.getMessage() );
//		}
	}
}
