/* Generated by AN DISI Unibo */ 
package it.unibo.ctxBlsCustom;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainCtxBlsCustom  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = "./srcMore/it/unibo/ctxBlsCustom";
	return QActorContext.initQActorSystem(
		"ctxblscustom", "./srcMore/it/unibo/ctxBlsCustom/blscustom.pl", 
		"./srcMore/it/unibo/ctxBlsCustom/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	QActorContext ctx = initTheContext();
} 	
}
