/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.qacontrolhl;
import it.unibo.baseEnv.basicFrame.EnvFrame;
import it.unibo.custom.gui.CustomBlsGui;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Qacontrolhl extends AbstractQacontrolhl { 
	public Qacontrolhl(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
 	
	public void  createButtonObject(String devType){
		if(  devType.equals("gui")) createButtonObjecGui();
 		if( env != null) {	//env is null if we use mock
			((EnvFrame) env).setSize(350, 300);
			((EnvFrame) env).setLocation(50, 150);
		}
 	}
	protected void createButtonObjecGui(){
 		CustomBlsGui.createCustomButtonGui(this);
	}
 	
}
