/* Generated by AN DISI Unibo */ 
package it.unibo.ctxE80Lgv;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainCtxE80Lgv  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = null;
	return QActorContext.initQActorSystem(
		"ctxe80lgv", "./srcMore/it/unibo/ctxE80Lgv/e80lgv.pl", 
		"./srcMore/it/unibo/ctxE80Lgv/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	QActorContext ctx = initTheContext();
} 	
}
