/* Generated by AN DISI Unibo */ 
package it.unibo.ctxBlsHlBlimkreactiveWeb;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.system.SituatedSysKb;
public class MainCtxBlsHlBlimkreactiveWeb  {
  
//MAIN
public static QActorContext initTheContext() throws Exception{
	IOutputEnvView outEnvView = SituatedSysKb.standardOutEnvView;
	String webDir = "./srcMore/it/unibo/ctxBlsHlBlimkreactiveWeb";
	return QActorContext.initQActorSystem(
		"ctxblshlblimkreactiveweb", "./srcMore/it/unibo/ctxBlsHlBlimkreactiveWeb/blshlblinkreactiveweb.pl", 
		"./srcMore/it/unibo/ctxBlsHlBlimkreactiveWeb/sysRules.pl", outEnvView,webDir,false);
}
public static void main(String[] args) throws Exception{
	QActorContext ctx = initTheContext();
} 	
}
