/* Generated by AN DISI Unibo */ 
package it.unibo.qaservercmds;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Qaservercmds extends QActorMsgQueue{
	public MsgHandle_Qaservercmds(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
