/* Generated by AN DISI Unibo */ 
package it.unibo.alarmemitter;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Alarmemitter extends QActorMsgQueue{
	public MsgHandle_Alarmemitter(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
