/* Generated by AN DISI Unibo */ 
/*
This code is generated only ONCE
*/
package it.unibo.qacontrolhlblinkreactive;
import it.unibo.baseEnv.basicFrame.EnvFrame;
import it.unibo.bls.highLevel.interfaces.IDevButton;
import it.unibo.bls.lowLevel.interfaces.IDeviceButtonImpl;
import it.unibo.custom.gui.CustomBlsGui;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.QActorContext;

public class Qacontrolhlblinkreactive extends AbstractQacontrolhlblinkreactive { 
	public Qacontrolhlblinkreactive(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
		super(actorId, myCtx, outEnvView);
	}
/*
 * ADDED BY THE APPLICATION DESIGNER	
 */
	CustomBlsGui gui;
	public void  createButtonObject(String devType, String btnName){
		if(  devType.equals("gui")) gui=CustomBlsGui.createCustomButtonGui(this,btnName);
 		if( env != null) {	//env is null if we use mock
			((EnvFrame) env).setSize(350, 300);
			((EnvFrame) env).setLocation(50, 150);
		}
 	}
//	public void createButtonObjecGui(String btnName){
// 		gui=CustomBlsGui.createCustomButtonGui(this,btnName);
//	}
	public void showTheButton(){
		gui.showTheButton();
	}
	public void hideTheButton(){
		gui.hideTheButton();	
	}

}
