/* Generated by AN DISI Unibo */ 
package it.unibo.cmdemitter;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Cmdemitter extends QActorMsgQueue{
	public MsgHandle_Cmdemitter(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
