/* Generated by AN DISI Unibo */ 
package it.unibo.lgvtester;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Lgvtester extends QActorMsgQueue{
	public MsgHandle_Lgvtester(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
