/* Generated by AN DISI Unibo */ 
package it.unibo.qamqttreceivet;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Qamqttreceivet extends QActorMsgQueue{
	public MsgHandle_Qamqttreceivet(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
