/* Generated by AN DISI Unibo */ 
package it.unibo.qajaactoivator;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Qajaactoivator extends QActorMsgQueue{
	public MsgHandle_Qajaactoivator(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
