/* Generated by AN DISI Unibo */ 
package it.unibo.ledblink;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Ledblink extends QActorMsgQueue{
	public MsgHandle_Ledblink(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
