/* Generated by AN DISI Unibo */ 
package it.unibo.radarguibase;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
public abstract class AbstractRadarguibase extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	 
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}
		public AbstractRadarguibase(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/radarguibase/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");		
			this.planFilePath = "./srcMore/it/unibo/radarguibase/plans.txt";
	  	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("waitSonarInfo",waitSonarInfo);
	    	stateTab.put("handleSonarInfo",handleSonarInfo);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "radarguibase tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("init",-1);
	    	String myselfName = "init";  
	    	temporaryStr = "\"RADAR init the GUI ... \"";
	    	println( temporaryStr );  
	    	parg = "activateGui"; 
	    	actorOpExecute(parg, false);	//OCT17		 
	    	//switchTo waitSonarInfo
	        switchToPlanAsNextState(pr, myselfName, "radarguibase_"+myselfName, 
	              "waitSonarInfo",false, false, null); 
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun waitSonarInfo = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp(getName()+"_waitSonarInfo",0);
	     pr.incNumIter(); 	
	    	String myselfName = "waitSonarInfo";  
	    	parg = "noOp"; 
	    	actorOpExecute(parg, false);	//OCT17		 
	    	//bbb
	     msgTransition( pr,myselfName,"radarguibase_"+myselfName,false,
	          new StateFun[]{stateTab.get("handleSonarInfo"), stateTab.get("handleSonarInfo") },//new StateFun[]
	          new String[]{"true","E","polar", "true","M","polarMsg" },
	          10000, "handleToutBuiltIn" );//msgTransition
	    }catch(Exception e_waitSonarInfo){  
	    	 println( getName() + " plan=waitSonarInfo WARNING:" + e_waitSonarInfo.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//waitSonarInfo
	    
	    StateFun handleSonarInfo = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("handleSonarInfo",-1);
	    	String myselfName = "handleSonarInfo";  
	    	//onMsg
	    	if( currentMessage != null && currentMessage.msgId().equals("polarMsg") ){
	    		String parg = "sendDataToGui(D,A)"; //it.unibo.xtext.qactor.impl.MsgTransSwitchImpl@b35c8d
	    		{/* ActorOp */
	    		parg =  updateVars( Term.createTerm("p(Distance,Angle)"), 
	    			                Term.createTerm("p(D,A)"), 
	    			                Term.createTerm(currentMessage.msgContent()), parg);
	    		if(parg != null) actorOpExecute(parg, false); //JUNE2017 OCT17
	    		}
	    	}
	    	//onEvent
	    	if( currentEvent != null && currentEvent.getEventId().equals("polar") ){
	    	 		String parg = "sendDataToGui(D,A)"; //it.unibo.xtext.qactor.impl.MsgTransSwitchImpl@b35c8d
	    	 		{/* ActorOp */
	    	 		parg =  updateVars( Term.createTerm("p(Distance,Angle)"), 
	    	 			                Term.createTerm("p(D,A)"), 
	    	 			                Term.createTerm(currentEvent.getMsg()), parg);
	    	 		if(parg != null) actorOpExecute(parg, false); //JUNE2017 OCT17
	    	 		}
	    	}
	    	repeatPlanNoTransition(pr,myselfName,"radarguibase_"+myselfName,false,true);
	    }catch(Exception e_handleSonarInfo){  
	    	 println( getName() + " plan=handleSonarInfo WARNING:" + e_handleSonarInfo.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//handleSonarInfo
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
	}
