/* Generated by AN DISI Unibo */ 
package it.unibo.radarguibase;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Radarguibase extends QActorMsgQueue{
	public MsgHandle_Radarguibase(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
