/* Generated by AN DISI Unibo */ 
package it.unibo.qacontrolhl;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Qacontrolhl extends QActorMsgQueue{
	public MsgHandle_Qacontrolhl(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
