/* Generated by AN DISI Unibo */ 
package it.unibo.qareceiver;
import it.unibo.qactors.PlanRepeat;
import it.unibo.qactors.QActorContext;
import it.unibo.qactors.StateExecMessage;
import it.unibo.qactors.QActorUtils;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.action.AsynchActionResult;
import it.unibo.qactors.action.IActorAction;
import it.unibo.qactors.action.IActorAction.ActionExecMode;
import it.unibo.qactors.action.IMsgQueue;
import it.unibo.qactors.akka.QActor;
import it.unibo.qactors.StateFun;
import java.util.Stack;
import java.util.Hashtable;
import java.util.concurrent.Callable;
import alice.tuprolog.Struct;
import alice.tuprolog.Term;
import it.unibo.qactors.action.ActorTimedAction;
public abstract class AbstractQareceiver extends QActor { 
	protected AsynchActionResult aar = null;
	protected boolean actionResult = true;
	protected alice.tuprolog.SolveInfo sol;
	protected String planFilePath    = null;
	protected String terminationEvId = "default";
	protected String parg="";
	protected boolean bres=false;
	protected IActorAction action;
	 
	
		protected static IOutputEnvView setTheEnv(IOutputEnvView outEnvView ){
			return outEnvView;
		}
		public AbstractQareceiver(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  throws Exception{
			super(actorId, myCtx,  
			"./srcMore/it/unibo/qareceiver/WorldTheory.pl",
			setTheEnv( outEnvView )  , "init");		
			this.planFilePath = "./srcMore/it/unibo/qareceiver/plans.txt";
	  	}
		@Override
		protected void doJob() throws Exception {
			String name  = getName().replace("_ctrl", "");
			mysupport = (IMsgQueue) QActorUtils.getQActor( name ); 
			initStateTable(); 
	 		initSensorSystem();
	 		history.push(stateTab.get( "init" ));
	  	 	autoSendStateExecMsg();
	  		//QActorContext.terminateQActorSystem(this);//todo
		} 	
		/* 
		* ------------------------------------------------------------
		* PLANS
		* ------------------------------------------------------------
		*/    
	    //genAkkaMshHandleStructure
	    protected void initStateTable(){  	
	    	stateTab.put("handleToutBuiltIn",handleToutBuiltIn);
	    	stateTab.put("init",init);
	    	stateTab.put("endOfwork",endOfwork);
	    }
	    StateFun handleToutBuiltIn = () -> {	
	    	try{	
	    		PlanRepeat pr = PlanRepeat.setUp("handleTout",-1);
	    		String myselfName = "handleToutBuiltIn";  
	    		println( "qareceiver tout : stops");  
	    		repeatPlanNoTransition(pr,myselfName,"application_"+myselfName,false,false);
	    	}catch(Exception e_handleToutBuiltIn){  
	    		println( getName() + " plan=handleToutBuiltIn WARNING:" + e_handleToutBuiltIn.getMessage() );
	    		QActorContext.terminateQActorSystem(this); 
	    	}
	    };//handleToutBuiltIn
	    
	    StateFun init = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("qareceiver_init",0);
	     pr.incNumIter(); 	
	    	String myselfName = "init";  
	    	temporaryStr = "\"qareceiver WAITS\"";
	    	println( temporaryStr );  
	    	//bbb
	    msgTransition( pr,myselfName,"qareceiver_"+myselfName,false,
	          new StateFun[]{stateTab.get("endOfwork"), //new state AD HOC to execute an action and resumeLastPlan
	          () -> {	
	          try{
	            PlanRepeat pr1 = PlanRepeat.setUp("adhocstate",-1);
	            //ActionSwitch for a message or event
	             if( currentMessage.msgContent().startsWith("info") ){
	            	//println("WARNING: variable substitution not yet implmented " ); 
	            	printCurrentMessage(false);
	             }
	            repeatPlanNoTransition(pr1,"adhocstate","adhocstate",false,true);
	          }catch(Exception e ){  
	             println( getName() + " plan=init WARNING:" + e.getMessage() );
	             //QActorContext.terminateQActorSystem(this); 
	          }
	          }
	          },
	          new String[]{"true","E","alarm", "true","M","info" },
	          10000, "handleToutBuiltIn" );
	    }catch(Exception e_init){  
	    	 println( getName() + " plan=init WARNING:" + e_init.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//init
	    
	    StateFun endOfwork = () -> {	
	    try{	
	     PlanRepeat pr = PlanRepeat.setUp("endOfwork",-1);
	    	String myselfName = "endOfwork";  
	    	//onEvent
	    	if( currentEvent.getEventId().equals("alarm") ){
	    	 		String parg = "endOfwork(X)";
	    	 		/* Print */
	    	 		parg =  updateVars( Term.createTerm("alarm(X)"), 
	    	 		                    Term.createTerm("alarm(X)"), 
	    	 			    		  	Term.createTerm(currentEvent.getMsg()), parg);
	    	 		if( parg != null ) println( parg );
	    	 }
	    	repeatPlanNoTransition(pr,myselfName,"qareceiver_"+myselfName,false,false);
	    }catch(Exception e_endOfwork){  
	    	 println( getName() + " plan=endOfwork WARNING:" + e_endOfwork.getMessage() );
	    	 QActorContext.terminateQActorSystem(this); 
	    }
	    };//endOfwork
	    
	    protected void initSensorSystem(){
	    	//doing nothing in a QActor
	    }
	
	}
