/* Generated by AN DISI Unibo */ 
package it.unibo.qafilewatcher;
import it.unibo.qactors.QActorContext;
import it.unibo.is.interfaces.IOutputEnvView;
import it.unibo.qactors.akka.QActorMsgQueue;

public class MsgHandle_Qafilewatcher extends QActorMsgQueue{
	public MsgHandle_Qafilewatcher(String actorId, QActorContext myCtx, IOutputEnvView outEnvView )  {
		super(actorId, myCtx, outEnvView);
	}
}
